[build]
  publish = "public"
  functions = "netlify/functions"
  command = "mkdir -p public && cp index.html public/index.html"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
